### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by kubukoz**
Hi! I made a couple improvements, given your version is the most popular I thought I'd contribute back.

- makes the local setup a bit better for testing (until I realized there are no tests :joy:)
- adds sounds
- increases the face count to 10
- you can turn off the sounds

Most faces are .webp as I could find decent images for them, but one is .png because it was missing and I had to make it myself. It's a shitpost anyway so I doubt you'll mind, but if you do I can convert it to webp for consistency.

### CODE REVIEW

**Review by Dulysse — APPROVED** [review]
Good job !

**Comment by XFox111** [comment]
@ttoowa pls merge asap

**Comment by AcrylicShrimp** [comment]
Thank you!

**Comment by reggermont** [comment]
@AcrylicShrimp can you please release a version? The extension is not updated in VSCode marketplace

**Comment by kubukoz** [comment]
For the time being, you can use my version, it includes all these changes: https://marketplace.visualstudio.com/items?itemName=kubukoz.incredibly-uncanny

**Comment by reggermont** [comment]
Thanks king :crown:

**Review by Garibaldi2000 — COMMENTED** [review]
6e02d8dc5fa13ddf25b8c23adb4c964426a8015d

**Pull request merged**
